services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  selenium:
    image: selenium/standalone-chrome:4.19.0
    shm_size: 2gb
    ports:
      - "4444:4444"   # Selenium Hub
      - "7900:7900"   # noVNC Web UI
    volumes:
      - selenium_downloads:/home/seluser/Downloads

  etl:
    build: .
    restart: always
    depends_on:
      - db
      - selenium
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SIGOS_USUARIO: ${SIGOS_USUARIO}
      SIGOS_SENHA: ${SIGOS_SENHA}
      HEADLESS: ${HEADLESS}
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - selenium_downloads:/app/downloads
      - etl_logs:/app/logs
    ports:
      - "8000:8000"   # API visível

volumes:
  pgdata:
  selenium_downloads:
  etl_logs: